file_uploads=On
upload_max_filesize=100M
post_max_size=120M
memory_limit=1024M
max_execution_time=300
max_input_time=300
display_errors=Off
log_errors=On
default_charset="UTF-8"
disable_functions=